Hardening the script a bit

diff --git a/ubuntu-build-image b/ubuntu-build-image
--- a/ubuntu-build-image
+++ b/ubuntu-build-image
@@ -32,9 +32,32 @@ fatal()
 cleanup()
 {
 	if [[ -n "$TMUX_PANE" ]]; then
-		echo -e "${Y}CLEANUP${Z}: turning off tmux logging ($_TMUX_LOG)"
+		echo -e "\n${Y}CLEANUP${Z}: turning off tmux logging ($_TMUX_LOG)"
 		tmux pipe-pane -t $TMUX_PANE
 	fi
+}
+cleanup_and_revert()
+{
+	echo -e "\n${Y}CLEANUP${Z}: extended cleanup of source tree changes"
+	# Changed files will be reverted
+	find "$BASEDIR" -type f -name '*.BAK-build-image'|while read fname; do
+		( set -x && mv "$fname" "${fname%%.BAK-build-image}" )
+	done
+	# Simply remove proxy.h if we moved it there
+	rm -f "$BASEDIR/release/src/router/neon/proxy.h"
+	# Unlink the toolchain symlink, in case we were asked to put one
+	[[ -n "$USE_SUDO" ]] && sudo unlink /opt/brcm
+	cleanup
+}
+install_prerequisites()
+{
+	echo -e "Will now attempt to install all prerequisite packages. This requires ${W}sudo${Z}."
+	echo -e "The command to be run is:\n ${W}sudo apt-get --no-install-recommends install ${Z}$PREREQ_PKGS"
+	read -p "Do you want to continue? (if not, hit Ctrl+C to abort)" ans
+	if [[ "${ans:0:1}" || "${ans:0:1}" ]]; then
+		sudo apt-get --no-install-recommends install $PREREQ_PKGS
+	fi
+	exit 0
 }
 if [[ -n "$TMUX_PANE" ]]; then
 	echo -e "${Y}NOTE:${Z} turning on tmux logging ($_TMUX_LOG)"
@@ -43,6 +66,9 @@ fi
 [[ -n "$ROUTERMDL" ]] || fatal help "you have to ${W}give the router model${Z} to build for."
 # Match the router model to find the correct base directory for make
 case ${ROUTERMDL^^} in
+	-P|--prereq*)
+		INSTALL_PREREQ=1
+		;;
 	RT-N16)
 		MKBASE="src-rt"
 		;;
@@ -66,8 +92,10 @@ let UBUREL=0x$(lsb_release -sr|tr -d '.')
 PREREQ_PKGS="autoconf automake bash bison bzip2 diffutils file flex g++ gawk gcc-multilib gettext gperf groff-base libncurses-dev libexpat1-dev libslang2 libssl-dev libtool libxml-parser-perl make patch perl pkg-config python sed shtool tar texinfo unzip zlib1g zlib1g-dev lib32z1-dev lib32stdc++6"
 # On Ubuntu 13.10 and later we check for two additional packages
 ((UBUREL >= 0x1310)) && PREREQ_PKGS="$PREREQ_PKGS automake1.11 libproxy-dev"
+# Did the user ask to install prerequisites instead?
+[[ -n "$INSTALL_PREREQ" ]] && install_prerequisites
 echo -en "${R}"
-dpkg-query --load-avail -l $PREREQ_PKGS > /dev/null || fatal "it appears you have packages missing (see above) that are required to build a firmware image.\nUse\n\tapt-get --no-install-recommends install ...\nto install the missing packages, then retry."
+dpkg-query --load-avail -l $PREREQ_PKGS > /dev/null || fatal "it appears you have packages missing (see above) that are required to build a firmware image.\nUse:\n\t${W}$0 --prereq${Z}\n\t${W}apt-get --no-install-recommends install${Z} ...\nto install the missing packages, then retry."
 echo -en "${Z}"
 # Special steps required on Ubuntu newer than or equal to 13.10
 if ((UBUREL >= 0x1310)); then
@@ -78,7 +106,7 @@ if ((UBUREL >= 0x1310)); then
 	# fix broken configure script for libdaemon
 	( cd "$BASEDIR/release/src/router/libdaemon" && aclocal ) || fatal "failed to fix broken configure script for libdaemon"
 	# fix broken configure script for libxml2
-	( cd "$BASEDIR/release/src/router/libxml2" && sed -i s/^AM_C_PROTOTYPES/#AM_C_PROTOTYPES/g configure.in && aclocal ) || fatal "failed to fix broken configure script for libxml2"
+	( cd "$BASEDIR/release/src/router/libxml2" && sed -i.BAK-build-image s/^AM_C_PROTOTYPES/#AM_C_PROTOTYPES/g configure.in && aclocal ) || fatal "failed to fix broken configure script for libxml2"
 fi
 # Clean up leftovers
 echo -e "${Y}NOTE:${Z} removing excess files"
@@ -98,6 +126,8 @@ else
 	done
 	# Instead of installing, we override some of the paths used in the build process
 	export TOOLCHAIN="$BASEDIR/tools/brcm/hndtools-mipsel-uclibc" # used in preconfigure scripts
+	# Set the trap to also revert the changes we made
+	trap cleanup_and_revert EXIT
 fi
 # Add the toolchain into the PATH
 export PATH="$PATH:$TOOLCHAIN/bin"
@@ -106,5 +136,7 @@ for i in mipsel-linux-addr2line mipsel-linux-ar mipsel-linux-as mipsel-linux-c++
 	$i --version > /dev/null 2>&1 || fatal "failed to execute $i"
 done
 # Do the make
+echo -e "${Y}NOTE:${Z} running ${W}make clean${Z}"
 make -C "$BASEDIR/release/$MKBASE" "TOOLCHAIN=$TOOLCHAIN" clean > /dev/null 2>&1
-make -C "$BASEDIR/release/$MKBASE" "TOOLCHAIN=$TOOLCHAIN" $ROUTERMDL
+echo -e "${Y}NOTE:${Z} running ${W}make ${ROUTERMDL,,}${Z}"
+make -C "$BASEDIR/release/$MKBASE" "TOOLCHAIN=$TOOLCHAIN" ${ROUTERMDL,,}
